import { Event } from '../utils/api';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Parent Support Group Meeting',
    description: 'Monthly support group for parents of children with special needs. Share experiences, ask questions, and connect with other families in a supportive environment.',
    date: '2024-02-15',
    time: '7:00 PM',
    location: 'Franklin Lakes Public Library',
    isVirtual: false,
    registrationRequired: false,
    category: 'Support Group',
    currentAttendees: 12,
    maxAttendees: 25
  },
  {
    id: '2',
    title: 'IEP Workshop: Understanding Your Rights',
    description: 'Learn how to effectively participate in your child\'s IEP process. This workshop covers parental rights, effective communication strategies, and how to advocate for your child\'s needs.',
    date: '2024-02-22',
    time: '6:30 PM',
    location: 'Virtual Meeting',
    isVirtual: true,
    virtualLink: 'https://zoom.us/j/123456789',
    registrationRequired: true,
    category: 'Workshop',
    currentAttendees: 8,
    maxAttendees: 20
  },
  {
    id: '3',
    title: 'Transition Planning Seminar',
    description: 'Planning for your child\'s transition from school to adult life. Learn about post-secondary options, vocational training, independent living skills, and community resources.',
    date: '2024-03-01',
    time: '7:00 PM',
    location: 'Franklin Lakes Community Center',
    isVirtual: false,
    registrationRequired: true,
    category: 'Workshop',
    currentAttendees: 15,
    maxAttendees: 30
  },
  {
    id: '4',
    title: 'Understanding ADHD: Strategies for Success',
    description: 'Educational workshop focused on understanding ADHD, effective strategies for supporting children with ADHD, and resources available in Franklin Lakes schools.',
    date: '2024-03-08',
    time: '6:00 PM',
    location: 'Franklin Lakes High School Auditorium',
    isVirtual: false,
    registrationRequired: false,
    category: 'Education',
    currentAttendees: 22,
    maxAttendees: 50
  },
  {
    id: '5',
    title: 'Autism Awareness and Support',
    description: 'Comprehensive workshop on autism spectrum disorders, early intervention strategies, and building a supportive community for families affected by autism.',
    date: '2024-03-15',
    time: '7:00 PM',
    location: 'Virtual Meeting',
    isVirtual: true,
    virtualLink: 'https://zoom.us/j/987654321',
    registrationRequired: true,
    category: 'Education',
    currentAttendees: 18,
    maxAttendees: 25
  },
  {
    id: '6',
    title: 'Legal Rights and Advocacy Training',
    description: 'Learn about special education law, your child\'s legal rights, and how to effectively advocate for appropriate services and accommodations.',
    date: '2024-03-22',
    time: '6:30 PM',
    location: 'Franklin Lakes Public Library',
    isVirtual: false,
    registrationRequired: true,
    category: 'Legal',
    currentAttendees: 10,
    maxAttendees: 20
  },
  {
    id: '7',
    title: 'Social Skills Development Workshop',
    description: 'Interactive workshop for parents and children focusing on developing social skills, building friendships, and navigating social situations.',
    date: '2024-04-05',
    time: '10:00 AM',
    location: 'Franklin Lakes Community Center',
    isVirtual: false,
    registrationRequired: true,
    category: 'Workshop',
    currentAttendees: 12,
    maxAttendees: 15
  },
  {
    id: '8',
    title: 'Technology and Learning Disabilities',
    description: 'Explore how technology can support learning for children with disabilities. Learn about assistive technology, apps, and digital tools that can enhance learning.',
    date: '2024-04-12',
    time: '7:00 PM',
    location: 'Franklin Lakes High School Computer Lab',
    isVirtual: false,
    registrationRequired: false,
    category: 'Technology',
    currentAttendees: 8,
    maxAttendees: 20
  },
  {
    id: '9',
    title: 'Summer Programs and Activities Fair',
    description: 'Discover summer programs, camps, and activities suitable for children with special needs. Meet program directors and learn about available options.',
    date: '2024-04-19',
    time: '6:00 PM',
    location: 'Franklin Lakes Community Center',
    isVirtual: false,
    registrationRequired: false,
    category: 'Information',
    currentAttendees: 35,
    maxAttendees: 100
  },
  {
    id: '10',
    title: 'Mental Health and Wellness for Families',
    description: 'Focus on mental health support for families of children with special needs. Learn about stress management, self-care, and accessing mental health resources.',
    date: '2024-04-26',
    time: '7:00 PM',
    location: 'Virtual Meeting',
    isVirtual: true,
    virtualLink: 'https://zoom.us/j/456789123',
    registrationRequired: true,
    category: 'Wellness',
    currentAttendees: 14,
    maxAttendees: 25
  }
]; 